### ISSUE TITLE
Cannot install.

### ISSUE THREAD

**Issue by th00mas88** [GourmandRecipeManager/gourmand#100]
Simply cannot install  using any method  - 

### Expected Behavior
gourmand installs 

### Current Behavior
installing with flatpak - I get this error 

pi@raspberrypi:~ $ sudo flatpak install gourmand-1.0.0.flatpak
error: The application io.github.GourmandRecipeManager.Gourmand/x86_64/master requires the runtime org.gnome.Platform/x86_64/40 which was not found

using AppImage  - no change and nothing seems to happen 

### Possible Solution
file name in install doc for flatpak is wrong  gourmond vs gourmet ?   this I have changed 

### Environment
running pi3b+ with latest OS and updated. 

unstalling using flatpak and appimage

**Comment by pled** [comment]
Hi,
You just need to install the runtime **org.gnome.Platform/x86_64/40** as mentioned in the error, which is required (see [here](https://docs.flatpak.org/en/latest/available-runtimes.html) for more information).
`sudo flatpak install org.gnome.Platform/x86_64/40`
should solve your problem.

**Comment by th00mas88** [comment]
nope :( 

`error: No remote refs found similar to ‘org.gnome.Platform/x86_64/40’


BUT this "worked" 

`flatpak install org.gnome.Platform/x86_64/40`

which then resulted in this 

`Info: (pinned) org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.


        ID                                  Branch Op Remote  Download
 1. [✓] org.freedesktop.Platform.GL.default 20.08  i  flathub   107.1 MB / 106.^[[23;59R        ID                                  Branch Op Remote  Download
 1. [✓] org.freedesktop.Platform.GL.default 20.08  i  flathub 107.1 MB / 106.4 MB
 2. [✗] org.freedesktop.Platform.openh264   2.0    i  flathub   1.8 MB / 1.5 MB
 3. [✓] org.gnome.Platform.Locale           40     i  flathub  17.9 kB / 333.9 MB
 4. [✓] org.gnome.Platform                  40     i  flathub 332.3 MB / 367.4 MB

Warning: While trying to apply extra data: apply_extra script failed, exit status 256
Installation complete.'


'pi@raspberrypi:~ $ sudo flatpak install gourmand-1.0.0.flatpak
error: The application io.github.GourmandRecipeManager.Gourmand/x86_64/master requires the runtime org.gnome.Platform/x86_64/40 which was not found`

**Comment by pled** [comment]
This is because you run last command with sudo, while you did not for the previous one. It is not the same environment for flatpak.

**Comment by th00mas88** [comment]
I think I understand that. 

But then 'sudo flatpak install org.gnome.Platform/x86_64/40' is not working 

I had tried the appimage method also and not working, which seems odd

**Comment by pled** [comment]
Check last column of `flatpak list` command. It tells you what is system or user  installed.
Then you may try something like : 
`sudo flatpak install --user gourmand-1.0.0.flatpak`
You have --user and --system parameters. Both packages have to be in the same env.

**Comment by pled** [comment]
For information, on my system, everything is installed as "system". 
```
$ flatpak list | grep gnome
GNOME Application Platform version 40	org.gnome.Platform		40	flathub	system
GNOME Application Platform version 41	org.gnome.Platform		41	flathub	system
$ flatpak list | grep gourmand
Gourmand	io.github.GourmandRecipeManager.Gourmand		master	gourmand-origin	system
```
The doc [here](https://docs.flatpak.org/en/latest/using-flatpak.html?highlight=--system#system-versus-user) says : 
"Flatpak commands can be run either system-wide or per-user. Applications and runtimes that are installed system-wide are available to all users on the system. Applications and runtimes that are installed per-user are only available to the users that installed them.
**Flatpak commands are run system-wide by default**. If you are installing applications for day-to-day usage, it is recommended to stick with this default behavior."
-=-
But why do you always use **sudo** for gourmand package installation ? Have you tried this : 
`flatpak install gourmand-1.0.0.flatpak` ?
I guess when using 'sudo', you are no more in your per-user env, thus the error.

**Comment by th00mas88** [comment]
Im wiping it all and starting again. 

BUT Using sudo because as on instructions it says.

**Comment by pled** [comment]
Actually, I try a new install into fresh Ubuntu VM, and face exactly the same issue ! :( More to come hopefully !

**Comment by pled** [comment]
I guess I got it : The flatpak repo must be added as "--system" and not "--user" : 
`flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo`
Doing that, all goes as it should ! :sunglasses: 
`sudo flatpak install gourmet-1.0.0.flatpak`
NOTE to keep system clean, I removed (flatpak remove) all what was installed neofre (as user) and now everything is as system looking at `flatpak list` command : 
```
$ flatpak list
Name         Application ID        Version Branch Origin           Installation
Gourmand     \u2026cipeManager.Gourmand         master gourmand4-origin system
Mesa         \u2026.Platform.GL.default 21.1.8  20.08  flathub          system
openh264     \u2026op.Platform.openh264 2.1.0   2.0    flathub          system
GNOME Appli\u2026 org.gnome.Platform            40     flathub          system
```

**Comment by th00mas88** [comment]
Feel slightly glad its not just me :)

but should it not be `sudo flatpak install gourmand-1.0.0.flatpak`

I will give it a whirl and see where we get to shortly

**Comment by pled** [comment]
This is just the filename actually !

**Comment by th00mas88** [comment]
installed and in accessories . but cannot run / open. 

```
`pi@raspberrypi:~ $ flatpak list
Name                  Application ID               Version Branch Origin           Installation
Gourmand              …rmandRecipeManager.Gourmand         master gourmand1-origin system
Mesa                  …desktop.Platform.GL.default 21.1.8  20.08  flathub          system
GNOME Application Pl… org.gnome.Platform                   40     flathub          system


```

```
`pi@raspberrypi:~ $ flatpak run io.github.GourmandRecipeManager.Gourmand
bwrap: execvp ldconfig: Exec format error
error: ldconfig failed, exit status 256

```
`

**Comment by pled** [comment]
Hmm.. This is probably related to your Raspberry arch. What is the output of `uname -a` command ?
- Rasp 3b+ is ARMv8 architecture if I am correct (ARM64), this explains why AppImage does not launch (it requires x86_64).
- Regarding Gourmand Flatpak package, the dev guys should tell us if it is ARM64 compatible. I did find the information, but it seems it is not... :disappointed:

**Comment by th00mas88** [comment]
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux



So this would be a need to rebuild and make a new pi? 


Might resolve the odd screen issue also.

**Comment by pled** [comment]
armv7l is 32 bits processor. I have no idea what gourmand needs to work on, it is probably not supported/tested on such arch, so cannot help you about this.

**Comment by th00mas88** [comment]
Thanks so much for all your help so far !

**Comment by cydanil** [comment]
Thank you both for this discussion.  
The flatpak and appimages are indeed targeting the x86 platforms (that is, Intel and AMD processors).  
To run Gourmand on a raspberry pi, would have to install Gourmand using the wheel, [as described in the installation documentation](https://github.com/GourmandRecipeManager/gourmand/blob/main/docs/installation.md#python-wheel).  

I'd like to provide flatpak or appimage for the raspberry pi, but there's a few things to fix first :)

**Comment by th00mas88** [comment]
Cool cool. 
Wheel give it a go later.


Is that in the instructions or did I miss it ? 

Same with the naming in instructions.

**Comment by th00mas88** [comment]
Perfect. 

@cydanil the text in the install page should maybe be updated ?
also . copying over a database from the "old" gourmet .. seems to fail .  any ideas ? or new help question

**Comment by cydanil** [comment]
I will look into what might make the copying of the database fail (or occur in the first place, on a fresh installation).  

Could elaborate on how the installation instruction should be updated? It's not too clear to me :slightly_smiling_face:

**Comment by th00mas88** [comment]
I think a new issue ? 
But the error for the import  - 

```
Doing import for  /home/pi/Desktop/recipes.db <plaintext_plugin.plaintext_importer_plugin.PlainTextImporterPlugin object at 0x6da32b08>
emit error 1 Error during Plain Text Importer Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gourmand/threadManager.py", line 104, in run
    self.do_run()
  File "/usr/local/lib/python3.9/dist-packages/gourmand/plugins/import_export/plaintext_plugin/plaintext_importer_plugin.py", line 25, in do_run
    del data
UnboundLocalError: local variable 'data' referenced before assignment

emit done
Running recipeMergerPlugin follow up post hook!
do_importer returns importer: <PlainTextImporter(importer, initial)>
import_filenames returns [<PlainTextImporter(importer, initial)>]
```




On install info - 

 FLATPAK / appget  should probely note the limitations 
 
 flatpak   - 

I think the comment above about `sudo flatpak install org.gnome.Platform/x86_64/40` should be added but that might be because im installing on a pi 
 should change `sudo flatpak install gourmet-1.0.0.flatpak` to` sudo flatpak install gourmand-1.0.0.flatpak`
 

 Wheel - 
 should change` sudo pip3 install gourmet-1.0.0-py3-none-any.whl` to `sudo pip3 install gourmand-1.0.0-py3-none-any.whl`

**Comment by pled** [comment]
My two cents about flatpak installation (on fresh Ubuntu 22.04) : 
The error is when adding the remote. There is no need to specify "--user" in the command, better to let the default (which will be system as flatpak doc mentions). Demo : 
```
$ sudo install flatpak
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```
Checking remote flathub install (installed system wide) : 
```
$ flatpak remote-list
Name    Options
flathub system
```
Now we can go with gourmand installation, required runtime will be automatically installed (you are prompted to, as mentioned in the documentation) : 
```
$ flatpak install gourmand-1.0.0.flatpak
Required runtime for io.github.GourmandRecipeManager.Gourmand/x86_64/master (runtime/org.gnome.Platform/x86_64/40) found in remote flathub
Do you want to install it? [Y/n]: Y
... etc...
 ```
Checking everything is installed (system wide) : 
```
$ flatpak list
Name                                  Application ID                           Version Branch Origin           Installation
Gourmand                              io.github.GourmandRecipeManager.Gourmand         master gourmand4-origin system
Mesa                                  org.freedesktop.Platform.GL.default      21.1.8  20.08  flathub          system
openh264                              org.freedesktop.Platform.openh264        2.1.0   2.0    flathub          system
GNOME Application Platform version 40 org.gnome.Platform                               40     flathub          system
Yaru Gtk Theme                        org.gtk.Gtk3theme.Yaru                           3.22   flathub          system
```
-=-
And true that there is still a remaining "gourmet-1.0.0.flatpak" filename that should be updated !

**Comment by pled** [comment]
@th00mas88 : regarding the import issue, you may workaround it by copying your gourmet `recipe.db` file to `~/.gourmand/reciped.db`. Then start gourmand.

**Comment by cydanil** [comment]
Thank you, I managed to reproduce this issue: it occurs when the gourmand directory exists, but the database is not there.  
This is because Gourmand checks to the directory, assuming a database is there.  
I will change the check to check for a database, and copy the default one if not available.

**Comment by th00mas88** [comment]
Cool. . update soon ? ? (not that im stressed about it.
