### ISSUE TITLE
No more "Import file" option with 1.1.0rc2

### ISSUE THREAD

**Issue by pled** [GourmandRecipeManager/gourmand#102]
### Steps to Reproduce
1. Open File menu

### Expected Behavior
An "Import file" item should be present.
See below screenshot, comparing 'File' menu between 1.0.0 and 1.1.0rc2  (note also there are some translation problems, as I use french OS) : 

### Current Behavior

![gourmand-import](https://user-images.githubusercontent.com/2879483/172174658-ade798ba-e887-4089-a724-988582a6748d.png)

### Environment
* Operating System: Debian sid or Ubuntu 22.04
* Version or commit id: 1.1.0rc2 
* Installed as Flatpak or Python package?: flatpak

**Comment by cydanil** [comment]
Thanks,  
Yes, the two option were merged into a single dialog: when clicking `import a recipe` you will be able to either browse for a file or paste a URL.

**Comment by pled** [comment]
Sorry, I should have gone a bit further : when  importing my personal database (recipes.db, 4,8 Mb), then I get this error, which says file is bigger than 100000 characters, and that I should use a text editor to split file : 
![Capture d’écran du 2022-06-07 10-09-49](https://user-images.githubusercontent.com/2879483/172330200-fed46c35-c79b-4e3e-a8cc-d7bf51404ebf.png)
So it looks like it is not expecting to import a database... :disappointed:

**Comment by cydanil** [comment]
Thanks for the clarification!  
It might be interesting to see whether the merging of databases is of interest, on the long run.
