### ISSUE TITLE
"Internet page" link does not open link anymore with 1.1.0rc2

### ISSUE THREAD

**Issue by pled** [GourmandRecipeManager/gourmand#105]
When opening recipe, you may have provided an "Internet link" as source of the recipe.
Using last 1.1.0rc2 version, clicking on link does not open link in browser anymore. Checked v1.0.0  was working fine (using for both flatpak packages).

![gourmand-link](https://user-images.githubusercontent.com/2879483/174025667-008030ff-178f-47d3-868e-d9a4f0dc65bb.png)

### Steps to Reproduce
1. Open any recipe with internet link provided
2. Click on Internet link
3. Nothing happens with 1.1..0rc2

### Expected Behavior
Link should open in browser.

### Environment
* Operating System: Ubuntu 22.04 or Debian 12 bookworm
* Version or commit id: 1.1.0rc2
* Installed as Flatpak or Python package?: flatpak

**Comment by pled** [comment]
Sure, here is the output : 
`Failed to open '/home/pascal/_http:/lesrecettesdejuliette.fr/article-aloo-palak-curry-de-pommes-de-terre-et-d-epinards-106816906.html': No such file or directory`
Link is preceded with $PWD_ , here :  `/home/pascal/_`

NOTE : I use Gnome as DE.

**Comment by cydanil** [comment]
Aha, thanks! I found the source of the issue, and made a fix for it :slightly_smiling_face:
