### ISSUE TITLE
Say 'Hello' to Tournant for Android! :-)

### ISSUE THREAD

**Issue by Zimbelstern** [GourmandRecipeManager/gourmand#112]
Hi,

a while ago, I developed [Tournant](https://tournant.zimbelstern.eu), a free and open-source Android app that can read Gourmand's XML files and display the recipes. (I've gathered a lot of recipes in Gourmand over the years but always had to move between the kitchen and my desktop PC.)

![Tournant](https://tournant.zimbelstern.eu/favicon-152.png)

I will try to add some more features now and then, so tell me what you think and what you would like to get implemented! I would be delighted if Tournant was a useful Gourmand supplement for some cooks out there! Any cooperation between Gourmand and Tournant will be greatly appreciated. Until now, Tournant hasn't really been noticed by anyone.

The source code of Tournant is [on GitHub](https://github.com/zimbelstern/Tournant).

PS: Sorry for using the issue tracker for that. I haven't found another place to put this in.

**Comment by tominglis** [comment]
Great, thanks for developing this!

**Comment by cydanil** [comment]
Hi @zimbelstern ,  
I like it and I thank you for your effort.  
Would you mind creating a PR updating the readme with a brief description and a link to the homepage?  

Thanks!

**Comment by zimbelstern** [comment]
After fixing some bugs and work in other projects, I finally had the time to figure out how Pull Requests work. ;-)

Regarding the further development of Tournant, I consider abandoning the XML files and using Gourmand's own internal database for recipe imports. That would make things a lot easier and it would pave the way for bidirectional synchronisation between Gourmand and Tournant.

However, I am not sure how to implement a synchronisation in a user-friendly way and without messing up Gourmand's own database. What are your thoughts on this?

**Comment by wyliecoyoteuk** [comment]
This app seems to be discontinued, shame.
