### ISSUE TITLE
recipe-scrapers requires a newer version of beautifulsoup4

### ISSUE THREAD

**Issue by MrShark** [GourmandRecipeManager/gourmand#115]
I wanted to import a recipe from ica.se that is supported by recipe-scrapers since yesterday, but the version requirements for beautifulsoup4 conflicted.

### Steps to Reproduce
Try to import https://www.ica.se/recept/mandelbakad-portabello-med-kramig-polenta-727104/ 

### Complications
After upgrading bs4 the importer failed due to prep_time and cook_time was missing and riced an exception so I had to work around that.

**Comment by MrShark** [comment]
Well, I'm not used to the github interface so some duplication in #116 116 :-)

**Comment by cydanil** [comment]
Thanks for reporting and fixing the issue, much appreciated :)
