### ISSUE TITLE
unable to add ingredients to recipe card, either by typing it in the add ingredient block or by adding it to the table manually

### ISSUE THREAD

**Issue by silverhikari** [GourmandRecipeManager/gourmand#141]
### Steps to Reproduce

1. open gourmand
2. go to any recipe card
3. go into editing ingredients
4. try to add ingredients

### Expected Behavior
the added ingredient appears in the table, with the ingredient name.

### Current Behavior
when adding the ingredient either via the add button or by adding a empty one and editing the ingredient name, both end up empty.

### Possible Solution

from reading the error log it seems to be caused by the a problem with the keyword "ingkey"

* Operating System: Linux/Manjaro
* Version or commit id: 42a8bfe9107ee40b3636e2a3307ad5af35e143e0
* Installed as Flatpak or Python package?: python via pipx
* python version: 3.10.8
* Error Log: https://paste.ee/p/l7rsi

**Comment by cydanil** [comment]
Thank you for taking the time to report the issue, much appreciated!  

I introduced this bug when doing a refactor a while back and failed to test correctly.  

I've made a fix for it and will merge once the CI is passed.  
As you're using Gourmand from source, you can benefit from it in a bit :slightly_smiling_face:   .  

I've made a follow-up ticket to refactor this part of the code cleanly and add better tests (which we do have, but are disabled for now :/  )

**Comment by silverhikari** [comment]
hey while this fix did fix adding ingredients by the "add ingredient" section and button, editing items that are already on the table do not work as this error happens
```
File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/reccard.py", line 2375, in ingtree_edited_cb
    self.ingController.undoable_update_ingredient_row(ref,d)
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/reccard.py", line 1772, in undoable_update_ingredient_row
    ).perform()
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/Undo.py", line 77, in perform
    self.action(*self.action_args)
  File "/home/silver/.local/pipx/venvs/gourmand/lib/python3.10/site-packages/gourmand/reccard.py", line 1768, in <lambda>
    lambda *args: self.update_ingredient_row(itr,**d),
TypeError: IngredientController.update_ingredient_row() got an unexpected keyword argument 'ingkey'
```
