### ISSUE TITLE
Debian possibly removing gourmand package??

### ISSUE THREAD

**Issue by jfabernathy** [GourmandRecipeManager/gourmand#159]
On one of my systems, Debian 12 bookworm, I was checking the Debian package tracker for gourmand and found this:

```
Marked for autoremoval on 17 January due to [gst-python1.0](https://tracker.debian.org/pkg/gst-python1.0): [#1055575](https://bugs.debian.org/1055575) high
Version 1.1.0+really1.1.0~rc3-3 of gourmand is marked for autoremoval from testing on Wed 17 Jan 2024. It depends (transitively) on [gst-python1.0](https://tracker.debian.org/pkg/gst-python1.0), affected by [#1055575](https://bugs.debian.org/1055575). You should try to prevent the removal by fixing these RC bugs.
```
[https://tracker.debian.org/pkg/gourmand](url)

I hope someone skilled can fix whatever issue this is before they remove the package.

**Comment by FriedrichFroebel** [comment]
Upstream ticket: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3170 This apparently has been reported there with a delay of one month and only one month left.

**Comment by FriedrichFroebel** [comment]
The GStreamer issue has been fixed upstream, thus this should not be relevant anymore.
