### ISSUE TITLE
Make use of recipe-scrapers for more generic web imports

### ISSUE THREAD

**Issue by cydanil** [GourmandRecipeManager/gourmand#18]
https://github.com/hhursev/recipe-scrapers provides a nice interface to scrape a number of websites, which could replace our importers for more flexible imports.  

This would also remove the burden for us to maintain importers on top of the application itself, as well as support way more websites than we could.

**Comment by cydanil** [comment]
I have a branch at that does this.  

The import dialog was reworked to be a single dialog for file and web imports, with validation of the supported urls:  

![image](https://user-images.githubusercontent.com/2159577/131833690-4723f793-1100-4d45-b737-8c90df9c86fc.png)

File import behaves the same.  

Web recipes are imported using `recipe-scrapers`, eg https://www.allrecipes.com/recipe/257887/lunch-biscuits/ :   

![image](https://user-images.githubusercontent.com/2159577/131834012-8a9f5704-a2a2-4da7-8e3d-a41eac4aec8d.png)


However, there's still a couple of items needing improvements:

1) Separate the web_importer from Gourmand internals;
2) Create web import status.

The motivation for 1 is to be able to plug in more web importers in a homogeneous should the need arise, and to decouple the import mechanism from user feedback.  

web imports still take a few seconds, mostly related to retrieving the recipe image. As such, it would be beneficial to have the import status in an info bar, as file imports do it.

**Comment by cydanil** [comment]
To finalize this feature, an import status still needs to be implemented:  recipes take a while to import, mostly due to retrieving and scaling images.

**Comment by eliotb** [comment]
Does this change mean that it will only be possible to import from one of the supported websites, rather than from any webpage with a recipe on it? 
If so, workaround is to save page as a file, or copy and paste text into plain text file, save that and then import it.
Related - to shortcut the copy,paste, save, import sequence would you be open to supporting direct import from the clipboard?

**Comment by founderio** [comment]
@cydanil Someone made a wrapper to text parsing here: https://github.com/hhursev/recipe-scrapers/issues/9#issuecomment-813036555

Maybe that can be utilized?

**Comment by cydanil** [comment]
Thanks for pointing me towards this comment, @founderio.  However, it seems to still expect SchemaOrg content.  
I tried to use it with a recipe using basic html (which I think will be the #1 need) to no avail.  

I picture the imports to be unstructured text as some variation of what's below:

```python
text = """
<html>
<title>Recipe title </title>
<br/>
Ingredients:

Ingredient Group 1:

    1 ⅓ cups all-purpose flour
    1 tablespoon granulated sugar
    ½ teaspoon salt
    ½ cup shortening
    3 ½ tablespoons cold water

Ingredient Group 2:

    2 cups mashed, cooked pumpkin, or about 1 1/2 pounds skin-on, raw pumpkin; Shortcut: You can substitute with canned pumpkin. Before you buy, you should check the label to make sure of what's in the can; if it's labeled "pumpkin pie filling" it's already spiced. If you plan to sweeten yourself with the ingredients below, go for unflavored canned pumpkin.
    1 (12 fluid ounce) can evaporated milk
    2 eggs, beaten
    ¾ cup packed brown sugar
    ½ teaspoon ground cinnamon
    ½ teaspoon ground ginger
    ½ teaspoon ground nutmeg
    ½ teaspoon salt
<br/>
whole pumpkin for pie

1. Instructions Part 1
blabla

2. Instructions Part 2
text

3. Instruction Part 3
text
</html>
"""
```

**Comment by eliotb** [comment]
> I like your suggesting of importing recipes by pasting selected text (or recipe file) in a window (the main window?).

I have just realised that the traditional importer (i.e. with the text pane and all the tag buttons on the right) almost does this now.
The text pane is already editable, and supports paste. So all that is needed is to be able to open it with the text pane empty.  Then the recipe can be pasted in there, edited, tagged and imported.
I tested this by "importing" a local text file, and then deleting the content of the text pane.

**Comment by cydanil** [comment]
This has been finalized in #67, where there's a couple of screencasts demonstrating drag and drop, similar to copy/paste.

I appreciate that supporting only a set of website looks like a regression in terms of functionality, even though it's compensated by plain text import.  
I will see how easily can I make any url importable, as it used to be.

Thanks for your feedback and ideas!
