### ISSUE TITLE
Wrong paste behaviour after using "Paste ingredients" option

### ISSUE THREAD

**Issue by cydanil** [GourmandRecipeManager/gourmand#19]
This is a copy of [this issue](https://github.com/kirienko/gourmet/issues/371).

When creating a new recipe, after having used "Paste ingredients" option from Ingredients page, if you use "Ctrl-v" in the Instructions page, the paste is done in the ingredients page. 

### Steps to Reproduce
1. Create a new recipe
2. Copy ingredients list from a recipe somewhere on the web for example.
3. In the Ingredients page, use the "Paste ingredients" option to paste your list of ingredients.
3. Now copy instructions from the recipe somewhere on the web.
4. Move to the Ingredients page in Gourmet, and use Ctrl-v to paste your instructions : the content is pasted into the ingredients page.

NOTE 1 : using right click, Paste option is ok, the content is correctly pasted in the instructions page.
NOTE 2 : if you don't use first the "Paste ingredients" option, then Ctrl-v wortks as expected in the instructions pages.

### Expected Behavior
Ctrl-v should paste at the current page.

### Environment
* Operating System: Ubuntu 20.04
* Version or commit id: 1.0.0 or 1.0.1 (same)
* Installed as Flatpak or Python package?: Flatpak

**Comment by cydanil** [comment]
This is partially solved: all tabs can independently be pasted to, but text is no longer automatically parsed on a paste in the ingredient tab.

**Comment by pled** [comment]
Hum... that feature (parsing ingredients list) is very useful when copying a recipe from the net. 
I prefer to use the "Right-clik-Paste" for instructions option workaround than loosing the parsing feature.
Just my opinion though.

**Comment by cydanil** [comment]
Absolutely! I will address this issue for the next release.

**Comment by cydanil** [comment]
I've fixed it as shown below:
![image](https://user-images.githubusercontent.com/2159577/132488977-42eb64ac-de75-4854-8232-ab063ea24db3.gif)
