### ISSUE TITLE
Wrong language for spell checker in Instructions window

### ISSUE THREAD

**Issue by pled** [GourmandRecipeManager/gourmand#29]
When using Gourmand on FR locale OS, the default language for "spell checker" is not set to French, resulting in red underlying for most of words. See picture below :
![gourmand-language](https://user-images.githubusercontent.com/2879483/131974242-115fb5d7-2918-4be0-ac11-a2bf8586b179.png)

### Steps to Reproduce
1. Create a new recipe and fill a description in french.
2. Most of words are underlying with red line.

### Expected Behavior
As OS locale is set to French, default language should be set to French, like below (set manually) :
![Capture d’écran de 2021-09-03 10-23-57](https://user-images.githubusercontent.com/2879483/131974745-5f650e83-7f30-4cfb-91aa-237f1231c3c6.png)

### Possible Solution
Set language manually like above.

### Environment
* Operating System: Ubuntu 20.04.3 FR
* Version or commit id: Gourmand 1.0.0
* Installed as Flatpak or Python package?: Flatpak
$ locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

**Comment by cydanil** [comment]
Thanks for the suggestion!  
I've implemented the default selection of the spellchecker language based on the locale.  

This will be added to the next release, which should be later this month :)
