### ISSUE TITLE
Small issue with importer from mycookbook

### ISSUE THREAD

**Issue by MimileVadrouille** [GourmandRecipeManager/gourmand#31]
Hi 

I am using an proprietary software my phone/tablet. I order to sync my receipt between my phone/tablet I am using a small script for converting that database into a mycookbook xml file. Then I can import all my receipt on Gourmet (or Gourmand  :-) ) 

the import of the mycookbook XML file skip the cuisine element. 

I should admit I love gourmand and the way that it take !  but generally I am not  cooking in front  of my computer that s way I am using the proprietary software on the phone!!! 

### Possible Solution

in plugins/import_export/mycookbook_plugin/mycookbook_importer.py

can be patch like this by adding the cuisine element:
               'cuisine': ('cuisine', ADD),
==> it shall look like this: 
    RECTAGS = {'title': ('title', IS),
               'url': ('link', ADD),
               'category': ('category', ADD),
               'cuisine': ('cuisine', ADD),
               'serving': ('servings', IS),
               'cooktime': ('cooktime', IS),
               'preptime': ('preptime', IS),
               'quantity': ('yields', IS),
               'rating': ('rating', IS),
               'source': ('source', IS),
               }

### Environment

* Operating System:
* Version or commit id:
* Installed as Flatpak or Python package?:

**Comment by cydanil** [comment]
Thank you @MimileVadrouille for reporting the issue and taking the time to look for a solution!  

It seems like a straightforward fix.  

Would it be possible for you to provide me a recipe file so that I can test the changes?  Thanks!

I'm also curious to know what app are you using on your phone, if that's okay :-)

**Comment by MimileVadrouille** [comment]
Hi,

yes of course I generate a relatively small file (no need to upload 350 receipt )

The software I am using is RecetteTek (https://www.recettetek.com/en/)

**Comment by MimileVadrouille** [comment]
here is a small mcb file to be imported - just replace the extension .zip by .mcb 

[backup_2021-02-14Test.rtk.zip](https://github.com/GourmandRecipeManager/gourmand/files/7131360/backup_2021-02-14Test.rtk.zip)

**Comment by cydanil** [comment]
Thanks a lot! I've made the fix as shown below:

![image](https://user-images.githubusercontent.com/2159577/132954885-5d4ea7ed-2efb-464f-b04b-16c9479c4877.png)

I aim to make a release towards the end of the month which will have this in :)

**Comment by MimileVadrouille** [comment]
@cydanil many thanks for this - That's great! :-)

I saw also that you made another very useful fix for the category (Split categories on comma only when saving recipes) 
Do you think that's possible also to apply a similar fix for the "cuisine" ? 

I am asking that because I use the "cuisine" field as a keyword. As generally I have more than one keyword attached to a receipt that could be also usfull to separate it with coma (or any other caracters such ,  ; : )

**Comment by cydanil** [comment]
Yep, that makes sense and is a feature that's been asked for for some years now (cuisines, collections, split databases...)
I will draft some requirements later and I'll ask you for feedback if that's fine?

**Comment by MimileVadrouille** [comment]
Hello @cydanil 

yes of course just send me it there is no pb to reread it :-)
