### ISSUE TITLE
Ampersand in instructions or notes renders them invisible on recipe card.

### ISSUE THREAD

**Issue by eliotb** [GourmandRecipeManager/gourmand#37]
### Steps to Reproduce

1. Create a new recipe, title e.g. "Test"
2. Edit instructions, enter the text "one & two"
3. Save
4. View recipe card

### Expected Behavior
See "one & two" in the instructions

### Current Behavior
Instructions is blank.

See in terminal: `(main.py:133088): Gtk-WARNING **: 22:49:51.718: Invalid markup string: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;`

_Note - text is rendered correctly in PDF export_

### Possible Solution

Workaround is to do as the Gtk warning suggests and replace the bare "&" with "&amp;" in the instruction text.

Better solution would be to do the escaping behind the scenes when rendering the recipe card.

### Environment

* Operating System: Ubuntu 20.04
* Version or commit id: 575d43a323d803c4fc1b9cfe9dea0744a86d12e8
* Installed from git checkout

**Comment by cydanil** [comment]
Thanks again for investigating the issue!  
The solution is indeed to escape the text before storing it.  

![image](https://user-images.githubusercontent.com/2159577/132952712-0f8981f5-4f8c-42d3-a9d7-e3f3a0d21ed8.png)

I've made a fix which should be merged in soon.  

I'm aiming to make a new release towards the end of the month.

Cheers,
Cyril
