### ISSUE TITLE
Better handling of french units

### ISSUE THREAD

**Issue by MimileVadrouille** [GourmandRecipeManager/gourmand#39]
When importing french receipt the units are not very well accepted. it is due to some untranslated units or missing units in src/gourmand/defaults/defaults_fr.py

examples: 
untranslated units:
mililiter is not translated to millilitre

missing stupid units - names aren"t really convertible, but we want them to be recognized as units.
("botte"  ,["botte",    "bottes"]),                                 # eg: botte de radis
("branche",["branche",  "branches"]),                               # eg: branches de thym
...

### Steps to Reproduce

1. import a french receipt - 

here is a sample: Just remove the extension .zip and import the file
[backup_2021-02-14Test.mcb.zip](https://github.com/GourmandRecipeManager/gourmand/files/7150026/backup_2021-02-14Test.mcb.zip)

check the "Test" receipt 

### Expected Behavior

units shall be recognized and then shown in the unit part of the ingredients

### Possible Solution

see my patch below 

### Environment

* Operating System: linux debian
* Version or commit id: src

I ll attach a proposition for the patch with some units.

[french_unit.patch.txt](https://github.com/GourmandRecipeManager/gourmand/files/7150022/french_unit.patch.txt)

nevertheless I have a few questions:

1) is it safe to replace of all occurrences of "tsp." (tee spoon) in src/gourmand/defaults/defaults_fr.py by something more understandable in french ? I am afraid to break the conversion and/or other things

i haven't done it. 

2) I hope I did it in a good way meaning thats not in po file that that patch shall be done

3) Maybe some improvement can be imported in the English language also:
eg:
("dag","g"):10,
("g", "mg"):1000,
("dg", "mg"):100,
("cg", "mg"):10,
I can do it if it can be usefull

**Comment by cydanil** [comment]
Hi @MimileVadrouille, 

Thanks for looking into this. It took me a while to get back to you as I wasn't that familiar with the unit handlings. 

Your suggestions make sense, and I would welcome your help.  

1. It's safe to replace `tsp.` with better units in `src/gourmand/defaults/defaults_fr.py` if you know of any.  
    The translations are made on a best effort basis and I welcome any improvements.  
2. Your approach is correct. I agree it's a bit confusing. The `po` files are for translating the user interface, whereas the `defaults_*.py` files are designed for Gourmand's internals.  
3. If you think the English defaults can be improved, please go ahead!  


Could you go ahead and make a PR? If you need help setting that up, let me know :)
