### ISSUE TITLE
ModuleNotFoundError when running Gourmand in Archlinux

### ISSUE THREAD

**Issue by sm3251** [GourmandRecipeManager/gourmand#42]
### Steps to Reproduce

1. Install gourmand in archlinux from AUR: 
2.
3.
4.

### Expected Behavior

When I start Gourmand, it loads up but I get a bunch of warnings and errors spit to the terminal. The output is in the file below:

[error.txt](https://github.com/GourmandRecipeManager/gourmand/files/7231201/error.txt)

Also, so far I have not been able to scrape a single recipe website, and I think the errors above may be related.  From the errors, it seems I may be missing a python package, but it seems all required packages are installed on my system. Any advice?

### Environment

* Operating System:
* Version or commit id:
* Installed as Flatpak or Python package?: python package from AUR.

**Comment by cydanil** [comment]
As you correctly inferred, the missing [`scrape_schema_recipe`](https://pypi.org/project/scrape-schema-recipe/) is blocking you from importing webpages.  

Looking at the [pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gourmand), it seems that only a subset of the dependencies are installed.  

Try installing the above package using pip.
