### ISSUE TITLE
"No Apps available" when clicking on "Web site" from About window

### ISSUE THREAD

**Issue by pled** [GourmandRecipeManager/gourmand#45]
Getting "No Apps available" window when clicking on "web site" link from the About window : 
![Capture d’écran de 2021-10-01 16-46-06](https://user-images.githubusercontent.com/2879483/135640659-96bb7e78-4ae5-467a-b44e-d21b94e3a13e.png)

![Capture d’écran de 2021-10-01 16-39-58](https://user-images.githubusercontent.com/2879483/135639463-4f35e4b8-0ce7-4b6a-af48-ed170e4be4e6.png)

### Steps to Reproduce
1. Open Gourmand
2. Click Help - About menu
3. Click "Web site" link
4. "No Apps available" window opens

### Expected Behavior
It should open web page in default browser, Firefox in my case

### Possible reason
Seems to be a typo error : when right clicking on web site link, then choosing "Copy link", I got the following link : "ihttps://github.com/GourmandRecipeManager/gourmand" => note the unexpected "i" starting the link.

### Environment
* Operating System: Ubuntu FR
* Version or commit id: 20.04
* Installed as Flatpak or Python package?: Flatpak Gourmand 1.0.0 version

**Comment by cydanil** [comment]
Thanks for this, I had not thought of testing this :) 
It could also be problematic when opening links within recipes, I'll check that.  

I'll update you on Monday.

**Comment by cydanil** [comment]
Thanks again, your suggestion was correct, it's a typo from using vim it seems.
