### ISSUE TITLE
Extensions Key Editor and Field editor does not work

### ISSUE THREAD

**Issue by MimileVadrouille** [GourmandRecipeManager/gourmand#50]
While testing the french patch  "Remaining english words on french OS #46 " I noticed that if we enable the extensions
- field_editor
- key_editor 
it generates some error 

Se my patch on the Closed PR #46 

### Steps to Reproduce

1. open Gourmand
2. open the menu "Preferences" ==> extensions
3. it the Tab Tools Enable Key Editor and Field editor

For Field editor it is better because it does not have a lot of side issue it is just does not work, but for Key Editor it is not possible to start gourmand afterwards

### Current Behavior

2 different behaviours are observed:
Key Editor  : It make gourmand to crash at the next opening..... that's wired and then we need to remove this reference in ~/.gourmand/preferences.toml 
Field editor: at least this does not make gourmand to crash it just report  errors in the terminal

### Possible Solution

These 2 extensions shall not be used right now unless it is ported (to GTKxxx??? or python3 ???) 

### Environment

* Operating System: Debian 11
* Version or commit id: master brach from 0711/2021
* Installed as Flatpak or Python package?: sources

**Comment by cydanil** [comment]
Fixing the field editor also help fixing the the batch editor.  

Thanks again :)

**Comment by MimileVadrouille** [comment]
great thanks
