### ISSUE TITLE
Importing old database

### ISSUE THREAD

**Issue by allenerenee** [GourmandRecipeManager/gourmand#74]
Maybe not really an issue, so I'm sorry if there would be a better place for this - I just am not sure where else to look.
I have just upgraded from MX19 to MX21 with a clean install - and I have no idea where Gourmet 1.0 stored my database, or what the file could have been named. Can anyone offer some insight?

**Comment by cydanil** [comment]
It should be in `~/.gourmet/recipes.db` or `~/.gourmand/recipes.db`

**Comment by cydanil** [comment]
The two applications are compatible, so you should be fine dropping the gourmet database in the gourmand folder:  
```bash
cp ~/.gourmet/recipes.db ~/.gourmand/recipes.db
```
:slightly_smiling_face:

**Comment by marillat** [comment]
This feature should be done by gourmand and not by users.
