### ISSUE TITLE
when trying to export all recipes as xml, the exporter fails and can not cancel the export

### ISSUE THREAD

**Issue by silverhikari** [GourmandRecipeManager/gourmand#75]
here is a log from the launching in console

log: https://paste.ee/p/m6ile

### Steps to Reproduce

1. open gourmand
2. click file
3. click export all recipes
4. click export

### Expected Behavior
the export finishes and a complete xml file of recipes is created.

### Current Behavior

here is a log from the launching in console

log: https://paste.ee/p/m6ile

### Possible Solution

my guess is that there is a string that is missing based upon the last message of the log.
### Environment

* Operating System: manjaro 21.2.1
* Version or commit id: f6b9b9bcb5761b40ce80477f628eef17978beca6
* Installed as Flatpak or Python package?: python, the python version is 3.9.7

**Comment by cydanil** [comment]
Thank you for reporting the issue!  
I suppose one of the recipe has `None` as one of the ingredient keys, and it should be possible to handle that.

I could not reproduce this behaviour, but I'll make a fix, would you be able to test it?  
Thanks!

**Comment by silverhikari** [comment]
just tested and it works!

**Comment by cydanil** [comment]
Nice, thanks for the confirmation 👍
