### ISSUE TITLE
Configuration files should be in ~/.config

### ISSUE THREAD

**Issue by marillat** [GourmandRecipeManager/gourmand#82]
Would be nice if gourmand can follow XDG Specification
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

This ~/.gourmand should be ~/.config/gourmand

Configuration files should be moved by gourmand itself not by the user.

**Comment by cydanil** [comment]
I agree this makes sense, thanks for bringing it up.  
I'll look into it in the coming days.
