### ISSUE TITLE
No access to the shopping list without adding recipes

### ISSUE THREAD

**Issue by l0f4r0** [GourmandRecipeManager/gourmand#90]
### Expected Behavior
Give direct access anytime to the shopping list.

### Current Behavior
It's only possible to consult the shopping list by adding recipes to it.
But sometimes, one just wants to see the shopping list without changing its state/content.

### Possible Solution
Add a dedicated button or menu entry "Consult the shopping list".

### Environment
* Operating System: Linux Debian 10 64bits
* Version or commit id: Gourmand-1.1.0rc2-x86_64.AppImage

**Comment by cydanil** [comment]
Thank you for the suggestion, I'm adding a button to the *Tools* menu:

![image](https://user-images.githubusercontent.com/2159577/171629456-4b853f16-3d2d-4b51-898b-a301a337a8c1.png)

Does that seem like a solution?

**Comment by l0f4r0** [comment]
> Does that seem like a solution?

Yeah, it seems great, thank you! :)

**NB**: as a location, maybe it would make more sense to add this shortcut to the "Go" menu instead of the "Tools" one?
Same remark with the "Open Trash" action.

**Comment by cydanil** [comment]
That makes sense, thanks:

![image](https://user-images.githubusercontent.com/2159577/171670690-e93df00e-f990-476c-af4d-ad1943725688.png)
