### ISSUE TITLE
Incomplete french translations in the GUI

### ISSUE THREAD

**Issue by l0f4r0** [GourmandRecipeManager/gourmand#91]
### Expected Behavior
Total GUI translation into french.

### Current Behavior
Some parts of the interface have not been translated into french yet:

- Main menu:
```
- Fichier > "Import Recipe" (should be "Importer une recette")
- Actions > "Add to Shopping List" (should be "Ajouter à la liste de courses")
- Actions > "Copy recipes" (should be "Copier la/les recette(s)")
- Actions > "Paste recipe" (should be "Coller la/les recette(s)")
```
_NB_: Fichier > "Nouveau" would be better formulated as "Créer une nouvelle recette".

- Main toolbar:
```
- Button "Add to Shopping List" (should be "Ajouter à la liste de courses")
```

- Navigation toolbar:
```
- "Browse Recipes" (should be "Naviguer entre les recettes")
```

- _Import Recipe_ dialog:
```
- "Enter a recipe file path or website address" (should be "Entrer le chemin ou l'adresse web vers une recette")
- "Location" (should be "Emplacement")
- Button "Browse File(s)..." (should be "Ouvrir le navigateur de fichiers")
```

- _Trash_ view (buttons on the bottom):
```
- "Empty trash" / "Delete permanently" / "Undelete" (should be "Vider la corbeille" / "Supprimer définitivement" / "Rétablir" respectively)
```

- Shopping List (table columns):

```
- "Item" (should be "Ingrédient")
- "Amount" (shoud be "Quantité")
```

- Search results:
```
- "x recipes" (should be "x recette(s)")
```

- _Preferences_ dialog:
```
- Vue par liste > "Show toolbar" (should be "Montrer la barre d'outils")
- Liste de courses > "What should Gourmand do with Optional Ingredients when adding recipes to the shopping list?" (should be "Que doit faire Gourmand avec les ingrédients facultatifs quand des recettes sont ajoutées à la liste de courses ?")
```

- And the whole _Help_ dialog...

### Possible Solution
Complete the french translation.

### Environment
* Operating System: Linux Debian 10 64bits
* Version or commit id:Gourmand-1.1.0rc2-x86_64.AppImage

**Comment by cydanil** [comment]
Thank you!  
 I'm not fluent in this language, but it seems like you'd be a good fit to update the translation :wink: 
 Would you like to go ahead and update it?  
There is some [documentation here](https://github.com/GourmandRecipeManager/gourmand/blob/main/docs/contributing.md#translations), which I'd be happy to improve, should it be incomplete.

**Comment by MimileVadrouille** [comment]
Hi @cydanil 

I did some work on the french translation long time ago. Most of them are OK except a few cases 

I did follow your documentation and because I did not want to screw up this repo I forked this repo ( i did not know also how to create and handle the pull request - so it was to learn a bit :-) 

On my fork you can find the updated french translation there:
https://github.com/MimileVadrouille/gourmand/pulls?q=is%3Apr+is%3Aclosed

is it OK ? if it is fine we can take it :-) 

Cheers

**Comment by cydanil** [comment]
This has been resolved by @MimileVadrouille who kindly updated the translation, thanks!
