### ISSUE TITLE
Manuallly adding items to the shopping list doesn't work

### ISSUE THREAD

**Issue by l0f4r0** [GourmandRecipeManager/gourmand#93]
### Steps to Reproduce
1. Select a recipe.
2. Click "Add to the shopping list".
3. Click "Add items" in the shopping list view.
4. Enter an item in the text field and click the "Add" button next to it.

### Expected Behavior
The manually entered item should be added to the shopping list.

### Current Behavior
Nothing happens. The entered item stays visible in the text field but is not added to the shopping list.

### Environment
* Operating System: Linux Debian 10 64bits
* Version or commit id: Gourmand-1.1.0rc2-x86_64.AppImage

**Comment by eliotb** [comment]
```
Traceback (most recent call last):
  File "/home/eliot/src/python/gourmand/src/gourmand/shopgui.py", line 876, in item_added
    dct = self.rd.parse_ingredient(txt)
AttributeError: 'RecData' object has no attribute 'parse_ingredient'
```

**Comment by cydanil** [comment]
Thank you for reporting the issue!  
It seems to have been introduced when refactoring.  
I've made a fix for it, which will be available in the next release :slightly_smiling_face: 

Cyril
